baseURL = 'https://dancebreak.stanford.edu'
languageCode = 'en-us'
title = 'Dancebreak'
theme = 'hextra'
enableGitInfo = true
ignoreLogs = ['warning-goldmark-raw-html']

[params]
editURL = { enable=true, base="https://github.com/stanford-dancebreak/stanford-dancebreak.github.io/edit/main/content" }

[params.navbar]
displayTitle = true
displayLogo = true

[params.navbar.logo]
path = "images/dancebreak.svg"
width = 48
height = 48

[params.page]
width = "wide"

[[menu.main]]
name = "Calendar"
pageRef = "/posts/25sum"
weight = 1

[[menu.main]]
name = "Info"
pageRef = "/info"
weight = 2

[[menu.main]]
name = "Archive"
pageRef = "/archive"
weight = 4

[[menu.main]]
name = "Search"
params = {type="search"}

[[menu.main]]
name = "GitHub"
url = "https://github.com/stanford-dancebreak/stanford-dancebreak.github.io"
params = {icon="github"}
