baseURL = 'https://dancebreak.stanford.edu'
languageCode = 'en-us'
title = 'Stanford Dancebreak'
theme = 'hextra'
enableGitInfo = true

[params]
editURL = { enable=true, base="https://github.com/stanford-dancebreak/stanford-dancebreak.github.io/edit/main/content" }

[params.navbar]
displayTitle = false
displayLogo = true

[params.navbar.logo]
path = "images/dancebreak-light.png"
dark = "images/dancebreak-dark.png"
width = 192
height = 24

[[menu.main]]
name = "Events"
pageRef = "/posts/25win-events"
weight = 1

[[menu.main]]
name = "Workshops"
pageRef = "/posts/25win-workshops"
weight = 1

[[menu.main]]
name = "Austria Fortnight"
pageRef = "/posts/25win-fortnight"
weight = 1

[[menu.main]]
name = "Info"
pageRef = "/info"
weight = 2

# [[menu.main]]
# name = "Announcements"
# pageRef = "/posts"
# weight = 3

[[menu.main]]
name = "Archive"
pageRef = "/archive"
weight = 4

[[menu.main]]
name = "Search"
params = {type="search"}

[[menu.main]]
name = "GitHub"
url = "https://github.com/stanford-dancebreak/stanford-dancebreak.github.io"
params = {icon="github"}
