name: Deploy Hugo site on Stanford AFS

on:
  workflow_run:
    workflows: ['Deploy Hugo site to Pages']
    types: [completed]
    branches:
      - 'main'
  workflow_dispatch:

concurrency:
  group: "afs"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AFS Sync
        run: |
          curl https://dancebreak.stanford.edu/cgi-bin/deploy.sh -X POST
